apiVersion: apps/v1
kind: Deployment
metadata:
  name: authM
  labels:
    app: authM
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authM
  template:
    metadata:
      labels:
        app: authM
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "authM"
        vault.hashicorp.com/agent-inject-secret-config: "authM/data/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "authM/data/config" -}}
          export DB_HOST="{{ .Data.data.db_host }}"
          export DB_PORT="{{ .Data.data.db_port }}"
          export DB_NAME="{{ .Data.data.db_name }}"
          export DB_USER="{{ .Data.data.db_user }}"
          export DB_PASSWORD="{{ .Data.data.db_password }}"
          export SMTP_HOST="{{ .Data.data.smtp_host }}"
          export SMTP_PORT="{{ .Data.data.smtp_port }}"
          export SMTP_USERNAME="{{ .Data.data.smtp_username }}"
          export SMTP_PASSWORD="{{ .Data.data.smtp_password }}"
          {{- end -}}
    spec:
      serviceAccountName: authM-vault-auth
      containers:
      - name: authM
        image: authM:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: CONFIG_FILE
          value: "/vault/secrets/config"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
---
apiVersion: v1
kind: Service
metadata:
  name: authM
spec:
  selector:
    app: authM
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 