apiVersion: v1
kind: ServiceAccount
metadata:
  name: authM-vault-auth
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: authM-vault-auth
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  config.hcl: |
    exit_after_auth = true
    pid_file = "/home/vault/pidfile"
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "authM"
        }
      }
    }
    template {
      contents = <<EOH
      {{- with secret "authM/data/config" }}
      DB_HOST={{ .Data.data.db_host }}
      DB_PORT={{ .Data.data.db_port }}
      DB_NAME={{ .Data.data.db_name }}
      DB_USER={{ .Data.data.db_user }}
      DB_PASSWORD={{ .Data.data.db_password }}
      SMTP_HOST={{ .Data.data.smtp_host }}
      SMTP_PORT={{ .Data.data.smtp_port }}
      SMTP_USERNAME={{ .Data.data.smtp_username }}
      SMTP_PASSWORD={{ .Data.data.smtp_password }}
      {{- end }}
      EOH
      destination = "/vault/secrets/config"
    } 